"""Demo commands in module.yaml -> VHS .tape files -> terminal video clips.

You never write .tape files by hand: the standard look and pacing
(theme, font size, typing speed, pauses) comes from course.yaml, and
the commands come from each scene's `demo` section.
Clips are only re-recorded when the commands or settings change.
"""
import os
import shutil

from common import fail, run, say, sha

NOT_PROGRAMS = {"cd", "export", "source", ".", "set", "unset", "alias", "echo",
                "printf", "true", "false", "exit", "history", "type", "clear", "for",
                "while", "if", "test", "[", "time"}


def quote(text, where):
    for q in ('"', "'", "`"):
        if q not in text:
            return f"{q}{text}{q}"
    fail(f"{where}: cannot type text that contains \", ' and ` at the same time: {text}")


def first_program(cmd):
    word = cmd.strip().split()[0] if cmd.strip() else ""
    if word in NOT_PROGRAMS or "=" in word or word.startswith(("/", "./", "$")):
        return None
    return word


def tape_text(scene, term, clip_name):
    demo = scene["demo"]
    where = f"scene '{scene['id']}'"
    pause = float(term.get("pause_after_output", 5))
    out = [
        "# AUTO-GENERATED by ./build.sh from module.yaml - edit module.yaml, not this file.",
        f'Output "{clip_name}"',
        "",
        f'Set Shell "{term.get("shell", "bash")}"',
        f'Set Theme "{term.get("theme", "Catppuccin Macchiato")}"',
        f"Set FontSize {term.get('font_size', 32)}",
        f"Set Width {term.get('width', 1920)}",
        f"Set Height {term.get('height', 1080)}",
        f"Set Padding {term.get('padding', 50)}",
        f"Set TypingSpeed {term.get('typing_speed', '150ms')}",
        f"Set PlaybackSpeed {term.get('playback_speed', 0.75)}",
        "",
    ]
    programs = []
    for c in demo["commands"]:
        p = first_program(str(c["run"]))
        if p and p not in programs:
            programs.append(p)
    out += [f"Require {p}" for p in programs]
    out += ["", "# Hidden preparation (not shown in the video)", "Hide"]
    setup = [ln for ln in str(demo.get("setup") or "").splitlines() if ln.strip()]
    for ln in setup + ["cd ~", "clear"]:
        out += [f"Type {quote(ln, where)}", "Enter"]
    out += ["Sleep 1s", "Show", ""]
    for i, c in enumerate(demo["commands"], 1):
        out.append(f"# Command {i}")
        if c.get("comment"):
            out += [f"Type {quote(str(c['comment']), where)}", "Sleep 1.5s", "Enter"]
        out += [f"Type {quote(str(c['run']), where)}", "Sleep 1s", "Enter",
                f"Sleep {float(c.get('wait', pause)):g}s", ""]
    return "\n".join(out) + "\n"


def record_demos(scenes, term, demo_dir):
    """Returns {scene_id: clip_path}."""
    demo_dir.mkdir(parents=True, exist_ok=True)
    clips = {}
    todo = [sc for sc in scenes if sc.get("demo")]
    if not todo:
        return clips
    if shutil.which("vhs") is None:
        fail("VHS is not installed, but this module has terminal demos.\n"
             "Run ./setup.sh (see docs/02-install-the-tools.md).")
    for n, sc in enumerate(todo, 1):
        clip = f"{sc['id']}.mp4"
        text = tape_text(sc, term, clip)
        tape = demo_dir / f"{sc['id']}.tape"
        stamp = demo_dir / f"{sc['id']}.hash"
        h = sha(text)
        if (demo_dir / clip).exists() and stamp.exists() and stamp.read_text() == h:
            say(f"  [{n}/{len(todo)}] {sc['id']}: unchanged, reusing recording")
        else:
            tape.write_text(text, encoding="utf-8")
            say(f"  [{n}/{len(todo)}] {sc['id']}: recording terminal (takes about a minute)...")
            run(["vhs", tape.name], cwd=demo_dir, env=os.environ.copy())
            stamp.write_text(h)
        clips[sc["id"]] = demo_dir / clip
    return clips
